// <auto-generated />
using Iglesia.Data;
using Iglesia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Iglesia.Migrations.Personas
{
    [DbContext(typeof(AuthDbContext))]
    partial class PersonasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Iglesia.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Causas")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("CiudadNacimiento")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("CiudadResidencia")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Denominacion")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Disciplinado")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("DocuIdentidad")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("ExpulsadoIns")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("FechaAceptado")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("FechaBautismo")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("FechaConversion")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Funciones")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Hijos")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("IglesiaAnterior")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Metas")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("MinisterioLlamado")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("MinisterioMayorFruto")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Ministerios")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("NivelEstudio")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("NombreIglesia")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("NombrePastor")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("PaisNacimiento")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("PaisResidencia")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Profesion")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Razon")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Respaldo")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("TelefonoEmp")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("apellido")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("celular")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("correo")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("fechaNacimiento")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("telefonoPer")
                        .HasColumnType("Nvarchar(100)");

                    b.HasKey("PersonaId");

                    b.ToTable("personas");
                });
#pragma warning restore 612, 618
        }
    }
}
